/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package country.searcher;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration;

@SpringBootApplication(exclude={DataSourceAutoConfiguration.class})
public class App {
    /*
        The JAR executable.
     */
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
